config/routes.rb
Rails.application.routes.draw do
  root to: 'movies#index'

  get '/login', to: 'sessions#new', as: 'signin'
  post '/login', to: 'sessions#create'

  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create', as: 'users'

  delete '/signout', to: 'sessions#destroy'
  get 'movies/search', to: 'movies#search', as: 'movie_search'

  get 'movies', to: 'movies#index'

  get 'movies/:id', to: 'movies#find'
  post 'movies/:id', to: 'movies#show', as: 'movie'

  get '/reviews/latest', to: 'reviews#latest', as: 'latest_reviews'


  #fix neste routes properly.
  resources :users, except: [:new] do
    resources :movies, only: [:index]
    end

    resources :movies do
    resources :reviews
    resources :users do
      resources :reviews, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews
  has_many :reviewers, through: :reviews, source: :user
  validates_uniqueness_of :title

  def self.order_by(type) 
    self.all.order(type)
  end

  def reviews_by(user)
    reviews.where(user: user)
  end

  def self.get_movie(params)
    res = HTTParty.get("http://www.omdbapi.com/?t=#{params}&apikey=78c60231")
  end
end

app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email, :name
  validates_uniqueness_of :email, { case_sensitive: false }
  has_many :reviews
  has_many :movies, -> { distinct }, through: :reviews

  def self.find_or_create_with_oauth(auth)
    u = User.find_by_uid(auth['uid']) || User.find_or_create_by_email(auth)
    u.email = auth['info']['email']
    u.uid = auth['uid']
    u.save
    u
end

  def self.find_or_create_by_email(auth)
    User.find_or_create_by(email: auth['info']['email']) do |u|
      u.uid = auth['uid']
      u.password = SecureRandom.hex(20)
      u.name = auth['info']['name']
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in
  before_action :redirect_if_logged_out

  
  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def logged_in
    !!current_user
  end

  def redirect_if_logged_out
    unless logged_in
      redirect_to signin_path, notice: "You must be logged in order to do that."
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :redirect_if_logged_out, only: %i[index find]

  def index
    if (params["user_id"])
      @user = User.find(params["user_id"])
      @movies = @user.movies
    else
      @movies = Movie.last(12)
    end
  end

  def new; end

  def search
    render :search
  end

  def show
    @movie = Movie.find_by(title: params[:search].capitalize) if params[:search].present?
    if @movie.nil?
      @movie = Movie.get_movie(params[:search])
      if @movie['Error']
        flash.notice = "#{@movie['Error']} Youre query: #{params[:search]}, Please try again."
        redirect_to root_path
      else
        @movie = create_movie(@movie)
      end
    else
      render :show
    end
  end

  def edit; end

  def find
    @movie = find_movie
    if @movie.nil? || @movie.title.nil?
      flash.alert = 'No movie found with this id'
      redirect_to root_path
    else
      @reviewers = @movie.reviewers
      render :show
    end
  end

  private

  def find_movie
    @movie = Movie.find_by(id: params[:id])
  end

  def create_movie(res)
    if logged_in
      movie = current_user.movies.build(
        title: res['Title'],
        year: res['Year'],
        rated: res['Rated'],
        genre: res['Genre'],
        write: res['Writer'],
        actors: res['Actors'],
        awards: res['Awards'],
        runtime: res['Runtime'],
        plot: res['Plot'],
        poster: res['Poster'],
        ratings: res['imdbRating']
      )
      if movie.save
        redirect_to movie_path(movie.id)
      else
        movie = Movie.find_by(title: movie.title)
        redirect_to movie_path(movie.id)
      end
    else
      movie = Movie.new(
        title: res['Title'],
        year: res['Year'],
        rated: res['Rated'],
        genre: res['Genre'],
        write: res['Writer'],
        actors: res['Actors'],
        awards: res['Awards'],
        runtime: res['Runtime'],
        plot: res['Plot'],
        poster: res['Poster'],
        ratings: res['imdbRating']
      )
      movie.save
      redirect_to movie_path(movie.id)
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_movie, except: [:latest]
  before_action :get_review, only: %i[edit destroy]
  skip_before_action :redirect_if_logged_out, only: %i[index latest], raise: false

  def index
    @reviews = if params[:user_id]
                 @movie.reviews_by(User.find(params[:user_id]))
               else
                 @movie.reviews.last(3)
                end
  end

  def new
    @review = @movie.reviews.new
  end

  def edit
    @review = get_review
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    if @review.save
      redirect_to movie_reviews_path
    else
      render 'new'
    end
  end

  def update
    if @movie.reviews.update(review_params)
      redirect_to movie_user_reviews_path(@movie.id, current_user), notice: 'Review updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @reviews.destroy
    redirect_to root_path, notice: 'Review deleted successfully.'
  end

  def latest
    @reviews = Review.last(6)
  end

  private

  def get_review
    @reviews = Review.find(params[:id])
  end

  def get_movie
    @movie = Movie.find(params[:movie_id]) || Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_if_logged_out, raise: false
  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @error = 'Incorrect username and/or password'
      render :new
    end
  end

    def google_auth
    u = User.find_or_create_with_oauth(auth)
    session[:user_id] = u.id

    redirect_to '/movies'
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_logged_out, only: [:new, :create]

  def new
    @user = User.new
end

  def show
    @user = find_user
    if @user.nil?
      flash.alert = 'No user found with this id'
      redirect_to root_path
    end
  end

  def create
    @user = User.new(user_data)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_data
    params.require(:user).permit(:name, :password, :email)
  end

  def find_user
    @user = User.find_by(id:params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def pic_available?
    !(@movie.poster.size < 4)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Moviez</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav>
    <div class="nav-wrapper red lighten-2">
      <a href="/" class="center brand-logo">Moviez</a>
      <ul class="right">
        <% if !current_user.nil? && !current_user.email.nil?%>
        <ul id="dropdown" class="dropdown-content">
          <li class="divider"></li>
          <li><%= link_to 'Log out', '/signout', method: 'delete' %></li>
          <li><%= link_to 'Profile', user_path(current_user.id), method: 'get' %></li>
          <li class="divider"></li>
        </ul>
        <a class="btn btn-large dropdown-button red lighten-2" data-activates="dropdown"><%=current_user.name%></a>
        <%else%>
        <li><%= link_to 'Register', signup_path, method:'get'%></li>
        <li><%= link_to 'Log in', signin_path, method:'get'%></li>
        <%end%>
        <li><%= link_to 'Search', root_path, method:'get'%></li>
        <li><%= link_to 'Latest movies', movies_path, method:'get'%></li>
        <li><%= link_to 'Latest reviews', latest_reviews_path, method:'get'%></li>
      </ul>
    </div>
  </nav>
  <br>
  <% flash.each do |type, msg| %>
  <div>
    <div class="center flow-text"><%= msg %></div>
  </div>
  <% end %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js">
  </script>
  <script>
  </script>
  <%= yield %>
</body>
   
</html>

app/views/movies/index.html.erb
<%if @movies.nil?%>
<div class="section center">
  <p class="flow-text ">There are currently no recent movie searches! Consider Looking up one!</p>
  <%=  link_to 'search a movie', movie_search_path , method:'get', class: 'btn btn-large indigo'%>
</div>

<%else%>
<div class="row left">Sort by:</div>
<%= form_tag movies_path, method: :get do %>

<%= submit_tag "ratings", name: :sort, class:"btn-small white-text indigo" %>
<%= submit_tag "ratings DESC", name: :sort, class:"btn-small white-text indigo" %>

<%= submit_tag "runtime", name: :sort, class: "btn-small white-text indigo" %>
<%= submit_tag "runtime DESC", name: :sort, class: "btn-small white-text indigo" %>

<%= submit_tag "year", name: :sort, class: "btn-small white-text indigo" %>
<%= submit_tag "year DESC", name: :sort, class: "btn-small white-text indigo" %>

<% end %>
</div>
<div class="container">
  <p class="flow-text center">Enjoy the latest movies searched by our users.</p>
</div>

<div class="row">
  <div class="col s12">
    <% @movies.each do |movie|%>
    <div class="col s4">
      <div class="card large">
        <div class="card-image">
          <% if (movie.poster.size < 4)%>
          <span>Image is not available through the api, if you'd like, you can report it
            <%= mail_to "cliprojectfis@gmail.com", "here"%>. thanks! :)</span>
          <%else%>
          <img src="<%=movie.poster%>">
          <%end%>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <p class="center"><strong>Title: <%=movie.title%>(<%=movie.runtime%>), <%=movie.year%>, Rating:
                <%=movie.ratings%></strong></p>

            <div class="section">
              <p><%=movie.plot%></p>
            </div>
            <div class="card-action">
            
              <%= link_to 'See reviews', movie_reviews_path(movie.id), class: 'btn indigo '%>
              <%= link_to 'Movie Page', movie_path(movie.id), class: 'btn indigo'%>
              <%= link_to 'New review', new_movie_review_path(movie.id), class: 'btn indigo'%>
              
            </div>
          </div>
        </div>
      </div>
    </div>
    <%end%>
    <%end%>
  </div>
</div>

app/views/movies/new.html.erb
sad

app/views/movies/search.html.erb
<br><br><br>

<% if @error %>
<div id="error_explanation">
    <p><%= @error %></p>
</div>
<% end %>

<br><br>
<h4 class="indigo-text center">Look for a Movie.</h5>
    <br><br>

    <div class="container">

        <section class="center col s4">
            <div class="container">

                <%= form_tag movie_search_path, :method => :post do %>

                <div class="input-field col s12">
                    <%= label_tag :search %>
                    <%= text_field_tag :search, '', :required => true%>
                </div>

                <div class='row'>
                    <br><%= submit_tag 'submit', :class => 'center btn btn-large waves-effect indigo' %>
                </div>
                <%end%>
            </div>
    </div>

app/views/movies/show.html.erb
 <% if @error %>
 <div id="error_explanation">
   <p><%= @error %></p>
 </div>
 <% end %>

 <div class="container col s12">
   <% if !@reviewers.nil?%>
   <%end%>
   <div class="section">
   <div class="col s6 center">
     <div class="card ">
       <div class="card-image ">
         <% if !pic_available?%>
         <span>Image is not available through the api, if you'd like, you can report it
           <%= mail_to "cliprojectfis@gmail.com", "here"%>. thanks! :)</span>
         <%else%>
         <img src="<%=@movie.poster%>">
         <%end%>

         <p class="flow-text">Title name:<%=@movie.title%></p>
         <div class="card-title">
         </div>
         <div class="section ">
           <span class="center">Awards: <%=@movie.awards%> IMDB Ratings: <%=@movie.ratings%>. Genre:
             <%=@movie.genre%>.<br>
         </div>
       </div>
       <div class="card-content">
         <p><%=@movie.plot%></p>
       </div>
       <div class="card-action">
         <div class="row">
           <%= link_to 'See reviews', movie_reviews_path(@movie.id), class: 'btn btn-large indigo right'%>
           <%= link_to 'New review', new_movie_review_path(@movie.id), class: 'btn btn-large indigo left'%>
         </div>
       </div>
     </div>
   </div>
 </div>
 </div>
    <div class="center">
    <% if !@reviewers.empty?%>
     <p class="flow-text">These are the latest users who reviewed that title:</p>
     <%@reviewers.each do |user|%>
     <p><%= link_to "#{user.name}", user_path(user), class: 'btn btn-medium indigo center' %></p>
      <%end%>
     <% else%>
     <p class="flow-text">There are no users who reviewed that title yet!</p>
     <%end%>
   </div>
 <style>
   .card img {
     max-height: 200px;
     object-fit: cover;
   }
 </style>

app/views/reviews/_form.html.erb
<div class="container center ">
  <div class="z-depth-2 grey lighten-4 " style="padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

    <%= form_for([@movie, @review]) do |f| %>

    <div class="range-field col s12">
      <%= f.label :rating %>
      <%=f.range_field :rating, in: 1..10, :step => 0.1%><br>
    </div>

    <div class="field col s12">
      <br><%= f.label :comment %>
      <%= f.text_area :comment, :placeholder => 'Explain your rating, so others can understand your point of view!', :required => true, minlength: 3%><br>
    </div>


    <div class="actions">
      <div class="row">
        <br><%= f.submit class: 'btn btn-larve indigo right' %>
        <%= link_to 'Back', movie_path(@movie), class: 'btn btn-medium indigo left' %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h5 class="center indigo white-text">Edit Review</h5>
<div class="section">
<%= render 'form', review: @review %>
</div>
|

app/views/reviews/index.html.erb
<div class="section center">
    <div class="row">
        <div class="card medium">

            <div class="card-image">
                <% if !pic_available?%>
                <span>Image is not available through the api, if you'd like, you can report it
                    <%= mail_to "cliprojectfis@gmail.com", "here"%>. thanks! :)</span>
                <%else%>
                <img src="<%=@movie.poster%>">
                <%end%>
            </div>

            <div class="card-title">
                <h5>Name:<%=@movie.title%></h5>
                <span>Ratings: <%=@movie.ratings%></span><br>
                <span>Actors: <%= @movie.actors%></span>
            </div>
        </div>

        <div class="row">
            <% if @movie.reviews.empty?%>
            <p class="flow-text ">There are currently no reviews for that movie! Consider adding one</p>
            <%else%>
        </div>

        <div class="section s12">
            <%@reviews.map do |review| %>
            <div class="card col s4 ">
                <p>Comment:<br>"<%= review.comment%>"</p>
                <p>Rating: <strong><%= review.rating%></strong></p>
            <% if review.user == current_user %>
              <%= link_to 'Edit', edit_movie_review_path(@movie, review), method:'get', class: 'btn indigo '%>
              <%= link_to 'Delete', movie_review_path(@movie, review), method:'delete', class: 'btn indigo '%>
            <% end %>
            </div>
            <%end%>
            <%end%>
        </div>
    </div>

    <div class="row s12">
        <p>Would you like to add a review?</p>
        <%= link_to 'New review', new_movie_review_path(@movie.id), class: 'btn indigo'%>
    </div>
</div>

app/views/reviews/latest.html.erb
<%if @reviews.empty?%>
<div class="section center">
  <p class="flow-text ">There are currently no reviews! Consider adding one!</p>
</div>
<%else%>
<div class="row">
  <div class="col s12">
    <% @reviews.each do |review|%>
    <div class="container">
      <div class="col s4">
        <div class="card small">
          <div class="card-stacked small">
            <div class="card-content center">

              <div class="row">
                <%@movie = Movie.where("id = #{review.movie_id}")%>
                <strong>Movie: <%=@movie.first.title%></strong>
              </div>

              <div class="row">
                <p>Rating: <%=review.rating%></p>
              </div>

              <div class="row">
                <p>Review: <%=review.comment%></p>
              </div>

              <div class="card-action">
                By: <%=review.user.name%>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    <%end%>
    <%end%>
  </div>
</div>

app/views/reviews/new.html.erb
<h3 class="center indigo flow-text white-text">New Review For <%=@movie.title%></h3>

<%= render 'form', review: @review %>

app/views/users/new.html.erb
<br><br>
<h4 class="indigo-text center">Create your new account</h5>
    <br><br>
    <section class="center col s4">
        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                <%= form_with(model: @user, local: true) do |form| %>

                <div class="input-field col s12">
                    <%= form.label :name %>
                    <%= form.text_field :name %>
                </div>

                <div class="input-field col s12">
                    <%= form.label :email %>
                    <%= form.email_field :email %>
                </div>

                <div class='row'>
                    <div class="input-field col s12">
                        <%= form.label :password %>
                        <%= form.password_field :password %>
                    </div>
                </div>

                <div class='row'>
                    <div class="actions">
                        <%= form.submit(class: 'center btn btn-large waves-effect indigo') %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        <%= link_to 'Log in with google!', '/auth/google_oauth2', method: 'post', class: 'btn btn-medium indigo'  %>

    </section>

app/views/users/show.html.erb
<% if @user.movies.empty?%>
<p class="flow-text center">There are no movies to be shown. Would you like to search for one?</p>
<div class="center">
  <%= link_to 'Search a movie', movie_search_path, class: 'btn indigo'%>
</div>
<%else%>
<div class="row">
  <div class="col s12">
    <% @user.movies.each do |movie|%>
    <div class="col s4">
      <div class="card medium">
        <div class="card-image">
          <% if (movie.poster.size < 4)%>
          <span>Image is not available through the api, if you'd like, you can report it
            <%= mail_to "cliprojectfis@gmail.com", "here"%>. thanks! :)</span>
          <%else%>
          <img src="<%=movie.poster%>">
          <%end%>
        </div>

        <div class="card-stacked">
          <div class="card-content">

            <strong class="center"><%=movie.title%></strong>
            <p><%=movie.plot%></p>

            <div class="card-action">
              <%= link_to 'See All Reviews', movie_reviews_path(movie), method:'get', class: 'btn indigo '%>
              <%= link_to 'See Your Reviews', movie_user_reviews_path(movie, current_user), method:'get', class: 'btn indigo '%>
            </div>
          </div>

        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>
<%end%>